
[bell]
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[debug]
highlight_damage = false
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[font]
size = 18

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = '''
printf "\033c"
'''
key = "K"
mode = "~Vi|~Search"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
decorations_theme_variant = "None"
dynamic_title = true
option_as_alt = "None"
resize_increments = false
title = "Alacritty"

[window.dimensions]
columns = 130
lines = 40

[general]
live_config_reload = true
import = ["/Users/ankurs4/.config/alacritty/themes/tokyo_night.toml"]
